### GET request to example server
@host = localhost:5000
@event_id = 4a761353-7eb4-4565-8491-7a4c6ee4404d

###  List all events
POST http://{{host}}
Content-Type: application/json

{
  "eventname":"Rock Concert",
  "filters": { "city": "Chicago" },
  "sorting": { "page_size": 50 }
}


### Create a new event

POST http://{{host}}/
Content-Type: application/json

{
  "organizer_name": "John Doe",
  "eventname": "Rock Concert",
  "city": "New York",
  "price": 150.50,
  "type": "concert"
}


### Get event by ID

GET http://{{host}}/
    ?id={{event_id}}


### Update event by ID
PUT http://{{host}}/
Content-Type: application/json

{
  "id": "{{event_id}}",
  "organizer_name": "Jane Smith",
  "eventname": "Jazz Festival",
  "city": "Chicago",
  "price": 150.99,
  "type": "festival"
}

### Delete event by ID
DELETE http://{{host}}/
    ?id={{event_id}}